### ISSUE TITLE
謎のアイテムがありましたがこれは……？

### ISSUE THREAD

**Issue by airosB** [miramiku/Laurus#28]
`[250928,[27],-5,"龍の　　　　　　","43232",0,[]]`
というアイテムがあり実際にステージでサジェストもされたのですが、存在するものでしょうか？

**Comment by miramiku** [comment]
以下の画像のアイテムになります。
![928-1](https://user-images.githubusercontent.com/1246535/28744909-cffe3818-74a6-11e7-9e4b-a5245ad9e6b3.png)

今現在（2017/07/29 21:30 ごろ）もアイテム名の修正は公式にされておりません。
「龍の」の文字の偏り具合より全角空白６つを入れてあります。エビデンス主義に則りデータベースを構築していますので、公式に修正があるまではアイテム名を修正する予定はありません…。

該当する上記アイテムを「龍の琴」と表記しているサイトもありますが、そのように表記された画像を私は確認していません。

**Comment by airosB** [comment]
実際に存在するアイテムなのですね……！（はじめて知りました）
スクショともどもありがとうございます！
このIssueはCloseさせていただきますー

**Comment by miramiku** [comment]
スクショはエビデンスとして１アイテムにつき３枚ずつ（衣装説明・属性詳細・入手方法）保管してあります。
エビデンスまだ５０％ほどしか採取できていませんが、100%揃えるのは無理ですが（入手先のないアイテムもいくつかあるので）ある程度揃ったら、データのエビデンスとして Laurus 内で必要に応じて表示できるようにするつもりです。

そして GitHub の通知がオフになっていたため気が付くのに遅れてすみません、先ほどの Issue のあと通知設定を編集したので今回は通知がきました＞＜；今後はもう少し早くレスポンスできると思います。

あとメモとして…Laurus の Disqus 内に投稿していたいだ同様の質問です。
https://miramiku.github.io/Laurus/#comment-3410624464

**Comment by airosB** [comment]
あ、ページ内にコメントがあったのですね。
広告ブロック系の拡張機能がコメント部分を要素ごと削除していたようで、気づきませんでした……！

**Comment by miramiku** [comment]
こちらでも構いませんよ(\*''▽'')
コメント欄も用意してますが…GitHub の Issues でも私の Twitter アカウントへリプライ・DM でも画像化してますがメールアドレスも公開してますから…私に伝わる方法であれば何でも構いませんー！
GitHub の Issues に人生ではじめて質問が来たのでちょっと嬉しかったです(\*^▽^\*)

**Comment by airosB** [comment]
おお そんな(笑 でも確かにGHで質問来るってないですね
では、また何か見つけましたらよさげな方法でご連絡させていただきます。どうもでした……！
