### ISSUE TITLE
読み込みの軽量化

### ISSUE THREAD

**Issue by miramiku** [miramiku/Laurus#29]
データベースをローカルに保存する。
wordrobe.json作成時にlastModified.jsonに日時を記録する。
ローカルデータベースのlastModifiedと同じ日時ならローカルからデータを読み込むようにする。

**Comment by yukyt** [comment]
今PCのChromeで確認したところ、httpヘッダのlast-modifiedを見てるのか、
Http response code 304で返ってきており、処理時間も10ms程度でした。
すでに実装済み あるいはスマホや特定ブラウザ向けでしょうか？

**Comment by miramiku** [comment]
特に何も実装しておりません…。minify 以外にも節約努力してますからね…
データ１件取り出してみて頂ければわかるかもしれませんが暗号に近いです…。stages.json も wordrobe.json も。

wordrobe.json は C# のプログラムで Excel から生成しています（Credit の resources に読み取り専用で公開しているものがオリジナルです）。stages も C# で大方生成し、ブラック・ホワイトリストはマニュアル追加ですね。なので unpack 版が存在します…それを gulp で minify してますね…。
想定する lastModified.json はたいした用量にはならないはずというかせいぜい２プロパティ＋α（想定外に追加したもの）だとおもいます。stages.json と wardrobe.json ですね…。wordrobe.json 生成時に一緒に lastModified.json も更新するように C# のプログラムをいじればいいかなと思っています。
stages.json はマニュアル更新になりそうですね…。lastModified.json は容量が少ないので minify かけなくてもいいでしょう。これだけ毎回読み込んでそのデータベースを Web から読み込むか、ローカルストレージに読み込むか判断させればいいかなと考えています。もちろん、ローカルストレージの最終取得日＝lastModified に記載されてる日時もローカルストレージに記録しますが。

ちょっと、あちらの方でのやり取りでもこの件に関して私の文章力に落ち度があったようなので…これは私がやりますね…データベースを生成する補助プログラムの関係なので…

**Comment by yukyt** [comment]
了解です！

lastModified.jsonのフォーマットは私もそんな形の想定でした！

ただ、修正前に現状の速度調べておこう、プラス、ヘッダのetagやlast-modifedで済むなら
そのほうがファイル用意しなくて済むし、自前で日付比較しなくてよさそう、
と思って確認したところ304レスポンスでしたので
これなら現状でもボディは転送されずにヘッダのみで済み、
小さいjsonを別途作っても転送量削減にならないのではないかなと。

ただstageとwardrobeで2回通信しているのを1回にまとめるのは有効だと思います。

ちなみにforce reloadで普通に読み込んでも20~90ms程度でした。さすがです 👍 

いずれにせよ、作るとしたらデータベース生成側との連携必須なので手を引きます。
お役に立てなくてすみません（T_T

**Comment by miramiku** [comment]
304 レスポンスの件、知識不足でスルーしてた感がありますが…
`Not Modified` なんですね…JavaScript からヘッダだけとる手段があればそれで済むのかもしれません…
そういう知識がなくて全く思いつかない方法でした…ちょっと検討させてください＞＜；
少なくとも今のデータ整理が済むまでは…ちょっと身動きができない状態で；；
データと本体のオールワークスは本体の方がおろそかにー…

知識が違いすぎて役に立ちすぎてですー(｀・ω・´) 色々ありがとうございます＞＜；

**Comment by yukyt** [comment]
今色々大変みたいですし無理なさらず！
返答とか数日放置しておいても大丈夫です。

304レスポンスの件はその通りです。
現状で既にブラウザとサーバが賢く働いてそういう動きになってるので、
このissue自体が既に達成済みになってます。

いろいろ使いこなしてらしたので、HTTP Response Codeも知ってる前提で話してしまいました。
分かりにくくてすみませんm(_ _)m

**Comment by miramiku** [comment]
忙しい日はたぶん数日おく可能性がありますー＞＜；まだ大丈夫(๑•ㅂ•)و✧

分かりにくいのではなく、私の知識が圧倒的に不足しているだけで問題ありませんー＞＜；
お勉強になります(｀・ω・´)
ネットワーク分野は苦手で結構わかってないこと多いですっ！
じゃあこの件はホールディング＆closeで！

あと、できれば公開の場だと話にくいことがあるので水面下（非公開）で話せる場所があったらと思いますー。Twitter の DM などなど…ほかの手段でも。いわゆるチャット＞＜；
