### ISSUE TITLE
非所持アイテムをWardrobeでも見えるようにする機能

### ISSUE THREAD

**Issue by yukyt** [miramiku/Laurus#33]
非所持状態にするとWardrobeの検索で出てこなくなるので、
入手後に所持状態を戻せるようにする機能。
単一/複数表示のように切り替え機能がいるかどうかは微妙なところ。

User Story
作成難度の高い衣装を非所持にした後、作成できたのでその衣装のみ所持状態に戻す。
あるいは過去イベントの衣装を非所持にした後、復刻されて入手できたのでその衣装のみ所持状態に戻す。

**Comment by miramiku** [comment]
おっと…機能の問題のようですね…
一応大切な事なので「使い方」に記載されているのですが…未所持にした場合、行った直後は Advisor から戻せますが…その後の操作は Wordrobe からしかムリです。
スペースの関係でちょっと分かりにくいですが…フィルタの「表示設定」の一番下に「未所持アイテムを表示する」という項目があるのでそれを有効にすると表示されます。

機能的な面について。
Wordrobe のメディウム（勝手につけてる用語です）を通して、フィルタの操作はできるので単数/複数表示の時にフィルタ設定も切り替えてもいいかもしれませんね。

現在、質素なデータベースなので Changelog の抽出コマンドより行っている状況ですが（Disqus のコメントで要望いただき実装したです）、おいおいコーデとガール級ドロップ品など集めてまとめて抽出できるようにしたいですね… Wordrobe の管轄になるのかな…

**Comment by yukyt** [comment]
すみません、気づきませんでしたm(_ _)m
閉じますー

**Comment by miramiku** [comment]
解決したならなによりです＞＜；
分かりにくくてすみませんでした…
